/* Interactive accessibility controls shared by all pages. */
(function(){'use strict';const body=document.body;const key='bolaLivreA11y';const defaults={font:0,contrast:false,dark:false,gray:false,links:false,focus:false,motion:window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches};let state=Object.assign({},defaults,JSON.parse(localStorage.getItem(key)||'{}'));const live=document.getElementById('live');
function announce(t){if(live){live.textContent='';setTimeout(()=>live.textContent=t,30)}}
function save(){localStorage.setItem(key,JSON.stringify(state));apply()}
function apply(){body.classList.toggle('font-large',state.font===1);body.classList.toggle('font-xlarge',state.font===2);body.classList.toggle('high-contrast',state.contrast);body.classList.toggle('dark',state.dark);body.classList.toggle('gray',state.gray);body.classList.toggle('highlight-links',state.links);body.classList.toggle('highlight-focus',state.focus);body.classList.toggle('reduce-motion',state.motion)}
function speak(text){if(!('speechSynthesis'in window)){announce('A leitura por voz não está disponível neste navegador.');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.95;window.speechSynthesis.speak(u);announce('Leitura iniciada')}
function pageText(){const main=document.querySelector('main');return main?main.innerText.replace(/\s+/g,' ').trim():''}
function action(a){switch(a){case'font-up':state.font=Math.min(2,state.font+1);announce('Fonte aumentada');break;case'font-down':state.font=Math.max(0,state.font-1);announce('Fonte diminuída');break;case'font-reset':state.font=0;announce('Fonte padrão restaurada');break;case'contrast':state.contrast=!state.contrast;announce(state.contrast?'Alto contraste ativado':'Alto contraste desativado');break;case'dark':state.dark=!state.dark;announce(state.dark?'Modo escuro ativado':'Modo escuro desativado');break;case'gray':state.gray=!state.gray;announce(state.gray?'Escala de cinza ativada':'Escala de cinza desativada');break;case'links':state.links=!state.links;announce(state.links?'Links destacados':'Destaque de links desativado');break;case'focus':state.focus=!state.focus;announce(state.focus?'Foco destacado':'Destaque de foco desativado');break;case'motion':state.motion=!state.motion;announce(state.motion?'Animações reduzidas':'Animações restauradas');break;case'reset':state=Object.assign({},defaults);announce('Configurações restauradas');break;case'speak':speak(document.activeElement.closest('article,section,.hero,.fact-card,.card')?.innerText||pageText());return;case'speak-page':speak(pageText());return;case'pause':window.speechSynthesis?.pause();announce('Leitura pausada');return;case'resume':window.speechSynthesis?.resume();announce('Leitura continuando');return;case'stop':window.speechSynthesis?.cancel();announce('Leitura parada');return;case'open-panel':document.getElementById('accessPanel').hidden=false;document.querySelector('#accessPanel button')?.focus();return;case'close-panel':document.getElementById('accessPanel').hidden=true;document.querySelector('.floating-access')?.focus();return}save()}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)action(el.dataset.action);if(e.target.id==='closeNotice'){document.getElementById('notice').remove();localStorage.setItem('bolaNotice','1')}});document.querySelector('.menu-toggle')?.addEventListener('click',function(){const n=document.getElementById('main-nav');const open=n.classList.toggle('open');this.setAttribute('aria-expanded',open)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){const p=document.getElementById('accessPanel');if(p&&!p.hidden){p.hidden=true;document.querySelector('.floating-access')?.focus()}}});if(localStorage.getItem('bolaNotice')==='1')document.getElementById('notice')?.remove();apply();})();
